<?php
/**
 * Created by PhpStorm.
 * User: Евгения
 * Date: 20.11.2017
 * Time: 16:07
 */

namespace modules\gallery\widgets;


use core\Html;
use core\Tools;
use core\Widget;
use modules\gallery\models\Image;

class Gallery extends Widget
{
    public static function show($module_name, $key = 0)
    {

        Html::instance()->setCss('/assets/modules/gallery/css/form.css');
        Html::instance()->setJs('/assets/modules/gallery/js/jquery.wallform.js');
        Html::instance()->setJs('/assets/modules/gallery/js/form.js');
        $imageModel = new Image();
        $temp_id = "";
        if (!$key) {
            $temp_id = Tools::generateRandomString();
        }
        $_SESSION['image_temp_name'] = $temp_id;
        $images = $imageModel->where(['module_name' => $module_name, 'key_id' => $key, 'temp_id' => $temp_id])->getAll();
        return Html::instance()->render(__DIR__ . "/templates/gallery.php", ['module_name' => $module_name, 'key_id' => $key, 'temp_id' => $temp_id, 'images' => $images]);
    }

    public static function possibilityList()
    {
        return ['show' => ['name' => 'Покажет галерею в нужном месте', 'parameters' => 'Название модуля и ключ доступа']];
    }

    public static function preview()
    {
        return parent::preview(); // TODO: Change the autogenerated stub
    }

}